### PR TITLE
addressing issue #1, training errors

### PR DESCRIPTION
**Pull request by sarahahtee**
once image resolution was changed from 512x512 to 256x256, training on slurm resulted in the following errors

error 1 (output file 'controlnet/controlnet-job.out') - 

```py
ImportError: Failed to load PyTorch C extensions:
    It appears that PyTorch has loaded the `torch/_C` folder
    of the PyTorch repository rather than the C extensions which
    are expected in the `torch._C` namespace. This can occur when
    using the `install` workflow. e.g.
        $ python setup.py install && python -c "import torch"

    This error can generally be solved using the `develop` workflow
        $ python setup.py develop && python -c "import torch"  # This should succeed
    or by running Python from a different directory.

```
OR error 2 (log file 'controlnet/hs_err_pid3495726.log'). this error persisted even with increasing memory allocation for training instance - 

```
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 8388608 bytes for Failed to reserve memory for metaspace
# Possible reasons:
#   The system is out of physical RAM or swap space
#   The process is running with CompressedOops enabled, and the Java Heap may be blocking the growth of the native heap
# Possible solutions:
#   Reduce memory load on the system
#   Increase physical memory or swap space
#   Check if swap backing store is full
#   Decrease Java heap size (-Xmx/-Xms)
#   Decrease number of Java threads
#   Decrease Java thread stack sizes (-Xss)
#   Set larger code cache with -XX:ReservedCodeCacheSize=
#   JVM is running with Unscaled Compressed Oops mode in which the Java heap is
#     placed in the first 4GB address space. The Java Heap base address is the
#     maximum limit for the native heap growth. Please use -XX:HeapBaseMinAddress
#     to set the Java Heap base and to place the Java Heap above 4GB virtual address.
# This output file may be truncated or incomplete.
#
#  Out of Memory Error (virtualSpaceNode.cpp:249), pid=3495726, tid=3495726
#
# JRE version: OpenJDK Runtime Environment GraalVM 22.3.0 (17.0.5+8) (build 17.0.5+8-jvmci-22.3-b08)
# Java VM: OpenJDK 64-Bit Server VM GraalVM 22.3.0 (17.0.5+8-jvmci-22.3-b08, mixed mode, sharing, tiered, jvmci, jvmci compiler, compressed oops, compressed class ptrs, serial gc, linux-amd64)
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /data/stariq/stariq/signwriting_illustration/controlnet/core.3495726)
#

---------------  S U M M A R Y ------------

Command Line: -XX:ThreadPriorityPolicy=1 -XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCIProduct -XX:JVMCIThreadsPerNativeLibraryRuntime=1 -XX:-UnlockExperimentalVMOptions -Dorg.graalvm.launcher.class=com.oracle.graal.python.shell.GraalPythonMain -Dorg.graalvm.launcher.executablename=/home/stariq/data/conda/envs/controlnet/bin/python 

Host: AMD EPYC 7702 64-Core Processor, 16 cores, 6G, Ubuntu 20.04.6 LTS
Time: Mon Mar 18 10:28:15 2024 CET elapsed time: 4.649533 seconds (0d 0h 0m 4s)
```

### CODE REVIEW

**Comment by AmitMY** [comment]
If you go into an interactive session:
```bash
srun --pty --time=1:0:0 --mem-per-cpu=7800 --cpus-per-task=2 bash -l
```
Then recreate a python environment:
```bash
conda remove --name controlnet --all
conda create --name controlnet python=3.11
```
Install torch
```bash
pip install torch
```
Can you then?
```bash
python -c "import torch"
```

---

Regardless, please add the pycache, out file and log file to git ignore. they should not be in this repository

**Comment by sarahahtee** [comment]
thanks!

after following the steps mentioned above, the following compatibility issue with 'opencv-contrib-python' arises:

```
ERROR: Could not find a version that satisfies the requirement opencv-contrib-python==4.3.0.36
ERROR: No matching distribution found for opencv-contrib-python==4.3.0.36
```

please note that the 'environment.yaml' file in the ControlNet repo specifies 'python=3.8.5' as a dependency. when checking the controlnet environment before running the training script, 'Python 3.11.8' is the active version but another check after executing the script shows a switch to 'GraalVM Python 3.8.5 (GraalVM CE JVM 22.3.0)'.

additionally, manually updating the 'environment.yaml' file to specify 'python=3.11.8' and 'opencv-contrib-python==4.9.0.80' produces the initial 'ImportError':

```
ImportError: Failed to load PyTorch C extensions:
```

**Comment by AmitMY** [comment]
Sounds like you are working with the [ControlNet](https://github.com/lllyasviel/ControlNet/) repository here and not with [huggingface](https://github.com/sign-language-processing/signwriting-illustration/tree/main/signwriting_illustration/controlnet_huggingface) 

Please work with the huggingface version, it is more stable and is generally better.

To work with it, there is no environment file.

To install, I follow this https://github.com/sign-language-processing/signwriting-illustration/blob/main/signwriting_illustration/controlnet_huggingface/train.sh#L23
```bash
conda create --name=diffusers python=3.11
conda activate diffusers
pip install diffusers transformers accelerate xformers wandb datasets argparse torchvision huggingface-hub
```

**Comment by sarahahtee** [comment]
great thanks! that worked :)

**Pull request closed without merging**
